### ISSUE TITLE
Wrong TS Type for the function

### ISSUE THREAD

**Issue by angelxmoreno** [sefinek24/is-image-header#19]
shouldn't the type of the function be `Promise<boolean>` ?

https://github.com/sefinek24/is-image-header/blob/e25d5b1e75dd6c400f2bee308340b9d59acb5e04/index.d.ts#L1

**Comment by angelxmoreno** [comment]
I had to add this to my typeRoots:
```ts
declare module "is-image-header" {
    function isImage(url: String): Promise<boolean>;;
    export = isImage;
}
```

**Comment by sefinek** [comment]
Yeah it should
https://github.com/sefinek24/is-image-header/blob/a602df7ea7c4949dfb8dd1d2903adf5bce6160c2/index.d.ts#L1
